config/routes.rb
Rails.application.routes.draw do
  
  #Need to namespace
  get '/campaigns/newest', to: 'campaigns#newest'
  get '/campaigns/most_raised', to: 'campaigns#most_raised'
  get '/campaigns/funded', to: 'campaigns#funded'

  
  resources :campaigns do
    resources :comments, only: [:new, :create]
    resources :donations, only: [:new, :create, :index ]
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations'  }
  resources :users, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "campaigns#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: "creator_id"
  has_many :donations
  has_many :users, through: :donations
  has_many :comments
  has_rich_text :description
  validates :title, length: { in: 5..75} 
  validates :picture, presence: true
  validates :goal, numericality: { only_integer: true, greater_than: 0 }
  validates :creator_id, presence: true
  scope :most_raised, -> { joins(:donations).group(:campaign_id).order("sum_amount DESC").sum(:amount)}


  def percent_raised
    if self.goal > 0 && self.donations.sum(:amount) > 0
      (self.donations.sum(:amount) * 100) / self.goal
    else
      0
    end
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :campaign
  validates :content, presence: true
  validates :user_id, presence: true
  validates :campaign_id, presence: true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :user
  belongs_to :campaign
  validates :amount, numericality: { only_iteger: true, greater_than: 0}
  validates :user_id, presence: true
  validates :campaign_id, presence: true

  def give_donation
    if self.user.funds >= self.amount
      self.user.funds -= self.amount
      self.user.save
    end
  end 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]


  has_many :created_campaigns, class_name: "Campaign", foreign_key: "creator_id"
  has_many :donations 
  has_many :campaigns, through: :donations
  has_many :comments
  validates :name, presence: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.photo = auth.info.image
      user.password = Devise.friendly_token[0,20]
    end      
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    

    def after_sign_in_path_for(resource)
        request.env['omniauth.origin'] || root_path
    end

    private

    def require_login 
        redirect_to new_user_session_path unless user_signed_in?
    end

    def set_campaign
        @campaign = Campaign.find_by(id: params[:id])
    end

    def authorize_campaign_creator
        redirect_to campaigns_path unless @campaign.creator == current_user
    end


    
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
    before_action :set_campaign, only: [:show, :edit, :update]
    before_action :require_login, only: [:new, :create, :edit, :update]
    before_action :authorize_campaign_creator, only: [:edit, :update]
    
    def newest
        @campaigns = Campaign.order(created_at: :desc)
    end
    
    def new 
        @campaign = Campaign.new
    end 

    def create
        @campaign = current_user.created_campaigns.build(campaign_params)

        if @campaign.save
            redirect_to campaign_path(@campaign)
        else
            render 'new'
        end
    end

    def show
        if user_signed_in?
            @comment = @campaign.comments.new(user_id: current_user.id)
        end
    end

    def index
        @campaigns = Campaign.all
    end

    def edit
    end

    def update 
        if @campaign.update(campaign_params)
            redirect_to campaign_path(@campaign)
        else 
            render 'edit'
        end
    end

    def most_raised
        # @campaigns = Campaign.all.sort_by { |n| n.donations.sum(:amount) }
        # @campaigns = Campaign.joins(:donations).group(:campaign_id).order("sum_amount DESC").sum(:amount)
        @campaigns = Campaign.most_raised
    end

    def funded 
        @campaigns = Campaign.all.select { |n| n.donations.sum(:amount) >=  n.goal }
    end

    private 

    def campaign_params
        params.require(:campaign).permit(:title, :description, :goal, :picture)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def new
        @comment = Comment.new(campaign_id: params[:campaign_id], user_id: current_user.id)
    end

    def create 
        @comment = Comment.new(comment_params)
        
        if @comment.save
            redirect_to @comment.campaign
        end
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :campaign_id, :user_id)
    end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
    
    before_action :require_login, only: [:new, :create]

    def new
      @campaign = Campaign.find_by(id: params[:campaign_id])
      @donation = @campaign.donations.build(user_id: current_user.id)
    end
    
    def create
      @donation = Donation.new(donation_params)
      @donation.give_donation && @donation.save
      if @donation.give_donation
        redirect_to campaign_path(@donation.campaign)
      else
        @msg = "Sorry, you don't have enough funds for that." 
        render 'new'
      end
    end

    def index
      @campaign = Campaign.find_by(id: params[:campaign_id])
    end


    
      private
      
      def donation_params
        params.require(:donation).permit(:amount, :user_id, :campaign_id)
      end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
    private

    def sign_up_params
      params.require(:user).permit(:name, :photo, :email, :password, :password_confirmation)
    end
  
    def account_update_params
      params.require(:user).permit(:name, :photo, :email, :password, :password_confirmation, :current_password)
    end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
       @user = User.from_omniauth(request.env["omniauth.auth"])
       sign_in_and_redirect @user      
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% end %>
  </figcaption>
</figure>

app/views/campaigns/_display_campaigns.html.erb
<div class="card-deck">
    <% @campaigns.each do |campaign|%>
        <div class="card mb-3" style="min-width: 33%; max-width: 448px">
            <img class="card-img-top" src="<%= campaign.picture %>" alt="Card image cap">
            
            <div class="card-body">
                <h5 class="card-title"><%= link_to campaign.title, campaign_path(campaign), class: 'text-dark' %></h5>
                
                <div class="progress">
                    <div class="progress-bar bg-success" role="progressbar" aria-valuenow="<%= campaign.percent_raised %>" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: <%= campaign.percent_raised %>%">
                        <%= campaign.percent_raised %>%
                    </div>
                </div>
                
                <p class="card-text"><span class="text-success h4">$<%= campaign.donations.sum(:amount) %></span> raised of
                <span class="text-success h4">$<%= campaign.goal %></span> Goal </p>
                
                <div class="row justify-content-center">
                    <%= link_to 'View Campaign', campaign_path(campaign), class: "btn btn-outline-success" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/campaigns/_form.html.erb
<div class="card-body">

        <% if @campaign.errors.any? %>
            <% @campaign.errors.full_messages.each do |msg| %>
                <div class="alert alert-danger" role="alert">
                    <%= msg %>
                </div>
            <% end %>
        <% end %>
        

        <%= form_for @campaign do |f| %>
            
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= f.label :description %>
                <%= f.rich_text_area :description %>
            </div>

            <div class="form-group">
                <%= f.label :goal %>
                <%= f.number_field :goal, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= f.label "Photo URL" %>
                <%= f.text_field :picture, class: 'form-control' %>
            </div>

            <div class="form-group">
                <%= f.submit "Create Campaign", class: 'btn btn-success' %>
            </div>

        <% end %>
    </div>

app/views/campaigns/edit.html.erb
<div class="card w-50 mx-auto">
    <div class="card-header">
        Edit Campaign
    </div>
    
    <%= render partial: "form" %>

</div>

app/views/campaigns/funded.html.erb
<%= render partial: 'display_campaigns'%>

app/views/campaigns/index.html.erb
<%= render partial: 'display_campaigns' %>

app/views/campaigns/most_raised.html.erb
<%= render partial: 'display_campaigns'%>

app/views/campaigns/new.html.erb
<div class="card w-50 mx-auto">
    <div class="card-header">
        Create a Campaign
    </div>
    
    <%= render partial: "form" %>

</div>

    

app/views/campaigns/newest.html.erb
<%= render partial: 'display_campaigns' %>

app/views/campaigns/show.html.erb
<div class="row">
    <div class="col-md-4 order-md-2 mb-4">
        <div class="card">
            <div class="card-body">
                <p>
                    Creator:<br>
                    <%= image_tag @campaign.creator.photo, class: "rounded-circle" %> <%= @campaign.creator.name %>
                </p>
                <p>
                    Goal:<br>
                    $<%= @campaign.goal %>
                </p>

                <div class="progress">
                    <div class="progress-bar bg-success" role="progressbar" aria-valuenow="<%= @campaign.percent_raised %>" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: <%= @campaign.percent_raised %>%">
                        <%= @campaign.percent_raised %>%
                    </div>
                </div>
                <p>
                    Raised:<br>
                    $<%= @campaign.donations.sum(:amount) %>
                </p>

                <%= button_to "Donate", new_campaign_donation_url(@campaign), class: "btn btn-success", method: 'get' %>
            </div>
        </div>
        
        <div class="card">
            <div class="card-header">
                Donations
            </div>
            <div class="card-body">
                <div class="row">
                    <% @campaign.donations.each do |donation| %>
                        <div class="card mt-1">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-auto">
                                        <%= image_tag donation.user.photo, class: "rounded-circle" %>
                                    </div>
                                    <div class="col">
                                        <%= donation.user.name %> <br> <span class="text-success">$<%= donation.amount %></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>



    <div class="col-md-8 order-md-1">
        <h1><%= @campaign.title %></h1>
        <p>
            <%= @campaign.description %>
        </p>
        <% if current_user == @campaign.creator %>
            <%= link_to 'Edit Campaign', edit_campaign_path(@campaign) %>
        <% end %>
    </div>
</div>

<div class="row">
    <div class="col-md-8 mt-2">
    <h5> Comments: </h5>
        <% @campaign.comments.each do |comment|  %>
            <p>
                <strong><%= comment.user.name %></strong> says:<br>
                <%= comment.content %>
            </p>
        <% end %>

        <% if user_signed_in? %>
            <%= render partial: 'comments/form' %>
        <% end %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@campaign, @comment] do |f| %>
    <%= f.hidden_field :campaign_id %>
    <%= f.hidden_field :user_id %>
    <div class="form-group">
        <%= f.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.submit "Add Comment", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/donations/_form.html.erb
<% if @msg %>
    <div class="alert alert-danger" role="alert">
        <%= @msg %>
    </div>
<% end %>

<%= form_for [@campaign, @donation] do |f| %>
    <%= f.hidden_field :campaign_id %>
    <%= f.hidden_field :user_id %>
    <div class="form-group">
        <%= f.label :amount, class: "form-control" %>
        <%= f.text_area :amount, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.submit "Confirm Donatiton", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/donations/index.html.erb
<div class="card w-50">
    <div class="card-header">
        All Donations
    </div>
    <div class="card-body">
        <div class="row">
            <% @campaign.donations.each do |donation| %>
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-auto">
                                 <%= image_tag donation.user.photo, class: "rounded-circle" %>
                            </div>
                            <div class="col">
                                <%= donation.user.name %> <br> <span class="text-success">$<%= donation.amount %></span>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/donations/new.html.erb
<%= render partial: 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaunchPad</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <nav class="navbar navbar-expand-md navbar-light border-bottom border-dark">
    <%= link_to image_tag("launchpad.png"), root_path, class: "navbar-brand" %>
    
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="<%= root_path %>" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Current Campaigns
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/campaigns/newest">Newest</a>
            <a class="dropdown-item" href="/campaigns/most_raised">Most Raised</a>
            <a class="dropdown-item" href="/campaigns/funded">Funded</a>
          </div>
        </li>
        <li class="nav-item">
          <%= link_to 'Launch a Campaign', new_campaign_path, class: "nav-link" %>
        </li>
      </ul>
      
      <div class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <%= link_to 'Profile', user_path(current_user), class: "nav-item nav-link small" %>  <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-item nav-link small") %>
        <% else %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-item nav-link small" %>  <%= link_to('Log In', new_user_session_path, class: "nav-item nav-link small") %>
        <% end %>  
      </div>
    </div>
</nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </div>
  </body>
</html>

app/views/users/show.html.erb
<div class="card">
    <div class="card-header">
        Profile
    </div>
    <div class="card-body">
        <div>
            Name: <%= @user.name %><br>
            <% if @user == current_user %>
                Email: <%= @user.email %><br>
                Funds: <%= @user.funds %>
            <% end %>
        </div>
        <div class="pt-3">
            <h6>Created Campaigns:</h6>
            <p>
            <% if @user.created_campaigns.exists? %>
                <% @user.created_campaigns.each do |campaign| %>
                    <%= link_to campaign.title, campaign_path(campaign) %><br>
                <% end %>
            <% else %>
                None :( 
            <% end %>
            </p>
        </div>
        <div class="pt-3">
            <h6>Recent Donations:</h6>
            <p>
            <% if @user.donations.exists? %>
                <% @user.donations.last(7).each do |donation| %>
                    <%= link_to "$#{donation.amount} - #{donation.campaign.title}", campaign_path(donation) %><br>
                <% end %>
            <% else %>
                None :( 
            <% end %>
            </p>
        </div>
        <div class="pt-3">
            <h6>Recent Comments:</h6>
            <p>
            <% if @user.comments.exists? %>
                <% @user.comments.last(7).each do |comment| %>
                    <%= link_to comment.campaign.title, campaign_path(comment) %><br>
                    <%= comment.content %><br><br>
                <% end %>
            <% else %>
                None :( 
            <% end %>
            </p>
        </div>
    </div>
</div>